server:
  port: 9090
  context-path: /ssm
  jsp-servlet:
    init-parameters:
      development: true #jsp开发模式部署 支持热部署
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity #默认类名,或者类名的首字母小写
logging:
  level:
    root: info #指定根日志
    com.baizhi.dao: debug #监听指定包中的日志 可以并列写多个
  #path: F:/log #指定日志生成路径,默认名字为 spring.log
  file: F:/log/aa.log #指定路径和名字生成日志